adshares/adpanel

src/app/auth/remind-password/remind-password.component.html
Change text on the button reset password.
=> 200 Change reset button password

src/app/advertiser/advertiser.service.ts, src/app/publisher/publisher.service.ts, src/environments/environment.dev-mock.ts, test/adserver_mock/mappings/campaigns_targeting__get.json, test/adserver_mock/mappings/sites_targeting__get.json
* Change requested api url #224 /sites/targeting & /campaigns/targeting => /options/*
=> 224 get targeting options calls uri changes (#231)

src/app/app.module.ts, src/app/auth/auth.service.ts, src/app/auth/register-confirm/register-confirm.component.ts, src/app/common/components/confirmation-alert/confirmation-alert.component.ts
Change url endpoint resend, add refresh time for visibility bar for email confirmed.
=> 228 resend and refresh visabillity active email.

src/app-settings/app-settings.ts, src/app/advertiser/advertiser.service.ts, src/app/publisher/edit-site/edit-site-basic-info/edit-site-basic-information.component.ts, src/app/publisher/publisher.service.ts
Fix regexp for validation site url and target url for campaign.
=> Fix target url regexp

.travis.yml, src/app/advertiser/advertiser.service.ts, src/app/advertiser/campaign-details/campaign-details.component.ts, src/app/common/request.interceptor.ts, src/app/models/campaign.model.ts, src/app/models/initial-state/campaign.ts, src/app/models/targeting-option.model.ts
=> Fix Campaign object

.travis.yml
=> update yarn build

src/app/models/initial-state/site.ts, src/app/models/site.model.ts, src/app/publisher/edit-site/edit-site-additional-targeting/edit-site-additional-targeting.component.ts, src/app/publisher/edit-site/edit-site-summary/edit-site-summary.component.html, src/app/publisher/edit-site/edit-site-summary/edit-site-summary.component.ts, src/app/publisher/edit-site/edit-site.component.ts, src/app/publisher/publisher.service.ts, src/app/publisher/resolvers/targeting-criteria.resolver.ts, src/app/publisher/site-details/site-details.component.html, src/app/publisher/site-details/site-details.component.ts, src/app/store/publisher/publisher.actions.ts, src/app/store/publisher/publisher.reducers.ts
In this PR:
- saving data on backend
- prevent showing double error modal on Internal server error
- prevent redirecting when saving failed
=> Fixed saving data on backend

.travis.yml, scripts/build.sh, scripts/install.sh
=> new config

src/app/publisher/edit-site/edit-site-additional-targeting/edit-site-additional-targeting.component.html, src/app/publisher/edit-site/edit-site-navigation/edit-site-navigation.component.html, src/app/publisher/edit-site/edit-site-navigation/edit-site-navigation.component.scss, src/app/publisher/edit-site/edit-site-navigation/edit-site-navigation.component.ts, src/app/publisher/edit-site/edit-site.component.html, src/app/publisher/publisher.module.ts
Copied navigation from common/components
=> PAN-18: rename targeting to filtering

src/app/advertiser/campaign-details/campaign-details.component.ts, src/app/common/common.module.ts, src/app/common/dialog/user-confirm-response-dialog/user-confirm-response-dialog.component.html, src/app/common/dialog/user-confirm-response-dialog/user-confirm-response-dialog.component.scss, src/app/common/dialog/user-confirm-response-dialog/user-confirm-response-dialog.component.ts, src/app/publisher/site-details/site-details.component.ts
It is connected with PAN-71, PAN-73.
=> PAN-108: Add user confirm dialog

src/app/publisher/edit-site/edit-site-basic-info/edit-site-basic-information.component.html, src/app/publisher/edit-site/edit-site-basic-info/edit-site-basic-information.component.scss, src/app/publisher/edit-site/edit-site-basic-info/edit-site-basic-information.component.ts, src/app/publisher/publisher.module.ts
Swapped mat select component with mat autocomplete to improve the user experience.
Adjusted styles to be consistent with the rest of the app.
=> UX improvement

src/app/models/site.model.ts, src/app/publisher/edit-site/edit-site-basic-info/edit-site-basic-information.component.html, src/app/publisher/edit-site/edit-site-basic-info/edit-site-basic-information.component.ts, src/app/publisher/edit-site/edit-site-create-ad-units/edit-site-create-ad-units.component.html, src/app/publisher/edit-site/edit-site-create-ad-units/edit-site-create-ad-units.component.ts, src/app/publisher/edit-site/edit-site-summary/edit-site-summary.component.ts, src/app/publisher/publisher.service.ts, src/app/publisher/site-details/site-details.component.html, src/app/publisher/site-details/site-details.component.ts, src/styles/_common.scss
In this PR:
- Removal of the additional step between site details and edit mode
- fixed edit mode inside edit basic site info
- fixed way of selecting ad unit size
=> PAN-96: Fix for selecting ad unit sizes for multiple zones

src/app/publisher/edit-site/edit-site-additional-targeting/edit-site-additional-targeting.component.html, src/app/publisher/edit-site/edit-site-additional-targeting/edit-site-additional-targeting.component.ts, src/app/publisher/edit-site/edit-site-basic-info/edit-site-basic-information.component.html, src/app/publisher/edit-site/edit-site-basic-info/edit-site-basic-information.component.ts, src/app/publisher/edit-site/edit-site-create-ad-units/edit-site-create-ad-units.component.html, src/app/publisher/edit-site/edit-site-create-ad-units/edit-site-create-ad-units.component.ts
- Navigate to site details (edit mode) and to matching create site step or dashboard (create site mode)
=> PAN-127: fix backwards navigation for edit mode

src/app/advertiser/edit-campaign/edit-campaign-additional-targeting/edit-campaign-additional-targeting.component.html, src/app/advertiser/edit-campaign/edit-campaign-additional-targeting/edit-campaign-additional-targeting.component.ts, src/app/store/advertiser/advertiser.actions.ts
After this PR user should be able to go to the campaign targeting edition page and edit targeting criteria and save changes.
=> PAN 41: Edit campaign targeting

src/app/advertiser/campaign-details/campaign-details.component.html, src/app/advertiser/campaign-list/campaign-list-item/campaign-list-item.component.html, src/app/advertiser/campaign-list/campaign-list.component.html, src/app/advertiser/edit-campaign/edit-campaign-basic-info/edit-campaign-basic-information.component.ts, src/app/advertiser/edit-campaign/edit-campaign-summary/edit-campaign-summary.component.html
Please, do not merge. It should be merged together with adServer PAN-152 
PR https://github.com/adshares/adserver/pull/202
=> PAN-93 Campaign list budget

src/app/advertiser/advertiser-routing.module.ts, src/app/advertiser/advertiser.service.ts, src/app/advertiser/campaign-details/ad-list/ad-list-item/ad-list-item.component.html, src/app/advertiser/campaign-details/ad-list/ad-list-item/ad-list-item.component.ts, src/app/advertiser/campaign-details/campaign-details.component.html, src/app/advertiser/campaign-details/campaign-details.component.ts, src/app/advertiser/edit-campaign/edit-campaign-additional-targeting/edit-campaign-additional-targeting.component.ts, src/app/advertiser/edit-campaign/edit-campaign-basic-info/edit-campaign-basic-information.component.html, src/app/advertiser/edit-campaign/edit-campaign-basic-info/edit-campaign-basic-information.component.ts, src/app/advertiser/edit-campaign/edit-campaign-create-ads/edit-campaign-create-ads.component.html, src/app/advertiser/edit-campaign/edit-campaign-create-ads/edit-campaign-create-ads.component.ts, src/app/common/components/targeting/targeting.helpers.ts, src/app/common/utilities/helpers.ts, src/app/publisher/edit-site/edit-site-additional-targeting/edit-site-additional-targeting.component.html, src/app/publisher/edit-site/edit-site-basic-info/edit-site-basic-information.component.html, src/app/publisher/edit-site/edit-site-create-ad-units/edit-site-create-ad-units.component.html, src/app/publisher/site-details/site-details.component.html, src/app/publisher/site-details/site-details.component.ts
In this pr:
- PAN-94:  Simplify campaign edition flow 
- PAN-157: Targeting should be displayed on the campaign details page
- PAN-159: simple HTML input validation
- PAN-83 - validate ad banners before sending request
=> Pan 94:  Simplify campaign edition flow  + campaign edition improvements

src/app/publisher/dashboard/dashboard.component.ts
Function moment without second parameter is used in Advertiser dashboard and works well.
=> Fix publisher chart invalid date on time axis

src/app/admin/dashboard/dashboard.component.ts, src/app/advertiser/advertiser.service.ts, src/app/advertiser/campaign-details/campaign-details.component.html, src/app/advertiser/campaign-details/campaign-details.component.ts, src/app/advertiser/dashboard/dashboard.component.ts, src/app/advertiser/edit-campaign/edit-campaign-additional-targeting/edit-campaign-additional-targeting.component.ts, src/app/advertiser/edit-campaign/edit-campaign-basic-info/edit-campaign-basic-information.component.ts, src/app/advertiser/edit-campaign/edit-campaign-create-ads/edit-campaign-create-ads.component.ts, src/app/advertiser/edit-campaign/edit-campaign-summary/edit-campaign-summary.component.ts, src/app/common/chart.service.ts, src/app/publisher/publisher.service.ts, src/app/store/advertiser/advertiser.actions.ts, src/app/store/advertiser/advertiser.effects.ts, src/app/store/advertiser/advertiser.reducers.ts, src/app/store/publisher/publisher.effects.ts
- Campaigns weren't properly updated, that was a cause of some serious app breaking problems solved in this pull request.
- protection for the occurrence when not every item has statistics data
=> Dispatch action to update site 

src/app/common/utilities/helpers.ts
This is fix by @m-pilarczyk from ads-operator-panel
https://github.com/adshares/ads-operator-panel/commit/79ddb3e0ce560e7b1fa6f254acb965d372429cb9#diff-9ce5ac96332c943d280d0c7311950887
=> PAN-154 Fix format money

src/app/common/components/targeting/targeting-display/targeting-display.component.scss, src/app/common/components/targeting/targeting-select/targeting-select.component.html, src/app/common/components/targeting/targeting-select/targeting-select.component.ts, src/styles/_forms.scss, src/styles/_material-override.scss
- remove 'ad selected button' - enable selection through a single click on a list item
- visual corrections
=> PAN-242: Targeting display and usability improvements

src/app/models/initial-state/site.ts, src/app/models/site.model.ts, src/app/models/targeting-option.model.ts, src/app/publisher/edit-site/edit-site-additional-targeting/edit-site-additional-targeting.component.ts, src/app/publisher/edit-site/edit-site.component.ts, src/app/publisher/site-details/site-details.component.ts, src/app/store/publisher/publisher.actions.ts
Merge together with SRV-232 from adserver
=> SRV-232 Move classified bools outside filtering

src/app/models/classifier.model.ts, src/app/publisher/classifier/classifier-filtering/classifier-filtering.component.html, src/app/publisher/classifier/classifier-filtering/classifier-filtering.component.scss, src/app/publisher/classifier/classifier-filtering/classifier-filtering.component.ts, src/app/publisher/classifier/classifier-list-item/classifier-list-item.component.scss, src/app/publisher/classifier/classifier.component.html, src/app/publisher/classifier/classifier.component.scss, src/app/publisher/classifier/classifier.component.ts, src/app/publisher/publisher-routing.module.ts, src/app/publisher/publisher.module.ts, src/app/publisher/publisher.service.ts, src/app/publisher/resolvers/matching-banner-sizes.resolver.ts, src/styles/_material-override.scss
merge after branch `PAN-268-add-classification-filter`
=>  PAN-275: Implement filtering for banner classification table

src/app/common/components/chart-filter/chart-filter.component.html, src/app/common/components/chart-filter/chart-filter.component.ts, src/app/common/components/chart/chart-settings.ts, src/app/common/components/chart/chart.component.ts
- all tics should be visible all the time
- increased max ticks rotation
- remove redundant onChange hook
- fixed selecting date to from date picker
- increased contrast and size of the chart fonts
- fixed filter title when selecting one day in the past (label should not say 'today')
=> PAN-179: Fixes and visual improvements for charts:

src/app/common/components/targeting/targeting-select/targeting-select.component.ts, src/app/common/components/targeting/targeting.helpers.ts
=> Targeting fix

package.json, src/app/admin/finances/earnings-settings/earnings-settings.component.html, src/app/admin/finances/earnings-settings/earnings-settings.component.scss, src/app/admin/finances/earnings-settings/earnings-settings.component.ts, src/app/admin/finances/finances-settings.component.html, src/app/admin/finances/finances-settings.component.scss, src/app/app.module.ts, src/main.ts, yarn.lock
- added hammerjs
-fixed formatting
=> PAN-303: Fix setting commission input behavior:

src/app/admin/admin.module.ts, src/app/admin/admin.service.ts, src/app/admin/dashboard/dashboard.component.html, src/app/admin/dashboard/dashboard.component.ts, src/app/admin/dashboard/panel-blockade/panel-blockade.component.html, src/app/admin/dashboard/panel-blockade/panel-blockade.component.ts, src/app/admin/dashboard/panel-blockade/panel.blockade.component.scss, src/app/admin/general-settings/general-settings.component.html, src/app/admin/general-settings/general-settings.component.scss, src/app/admin/general-settings/license/license.component.html, src/app/admin/general-settings/license/license.component.scss, src/app/admin/general-settings/license/license.component.ts, src/app/common/components/input/input.component.html, src/app/common/components/input/input.component.scss, src/app/common/components/input/input.component.ts, src/app/models/app-state.model.ts, src/app/models/settings.model.ts, src/app/store/admin/admin.actions.ts, src/app/store/admin/admin.effects.ts, src/app/store/admin/admin.reducers.ts, src/styles/_normalize.scss
- get license data
- show user license data
- when user is invalid show proper message and block panel
- show proper message when user has no license
- remove styles for increasing font size for higher resolutions
=> PAN-260: Enable license preview :

package.json, src/app/admin/finances/earnings-settings/earnings-settings.component.html, src/app/admin/finances/earnings-settings/earnings-settings.component.scss, src/app/admin/finances/earnings-settings/earnings-settings.component.ts, src/app/admin/finances/finances-settings.component.html, src/app/admin/finances/finances-settings.component.scss, src/app/app.module.ts, src/main.ts, yarn.lock
- added hammerjs
-fixed formatting
=> PAN-303: Fix setting commission input behavior: (#555)

src/app/common/dialog/success-snackbar/success-snackbar.component.html, src/app/common/dialog/success-snackbar/success-snackbar.component.ts, src/app/store/common/common.effects.ts
PAN-313: UX improvement - show snackbar with proper information after status update (#562)
=> PAN-313: UX improvement - show snackbar with proper information

package.json, src/app/admin/finances/earnings-settings/earnings-settings.component.html, src/app/admin/finances/earnings-settings/earnings-settings.component.scss, src/app/admin/finances/earnings-settings/earnings-settings.component.ts, src/app/admin/finances/finances-settings.component.html, src/app/admin/finances/finances-settings.component.scss, src/app/advertiser/campaign-details/ad-list/ad-list-item/ad-list-item.component.html, src/app/advertiser/campaign-list/campaign-list-item/campaign-list-item.component.html, src/app/advertiser/edit-campaign/edit-campaign-create-ads/edit-campaign-create-ads.component.ts, src/app/app.module.ts, src/app/common/components/table-navigation/table-navigation.component.ts, src/app/models/campaign.model.ts, src/app/models/initial-state/ad.ts, src/app/models/site.model.ts, src/app/publisher/site-details/ad-units/ad-units.component.html, src/app/publisher/site-list/site-list-item/site-list-item.component.html, src/app/settings/billing/billing-history/billing-history-withdrawal/billing-history-withdrawal.component.html, src/app/store/advertiser/advertiser.reducers.ts, src/main.ts, yarn.lock
- decrease font size in the billing history table
- change order of the elements in the tables
- implement banner name auto filling functionality
- make campaign table semantic
=> PAN-312: Visual fixes + banner name auto filling

src/app/advertiser/campaign-details/ad-list/ad-list-item/ad-list-item.component.html, src/app/advertiser/campaign-details/ad-list/ad-list-item/ad-list-item.component.scss, src/app/advertiser/campaign-list/campaign-list-item/campaign-list-item.component.html, src/app/advertiser/campaign-list/campaign-list-item/campaign-list-item.component.scss, src/app/publisher/site-list/site-list-item/site-list-item.component.html, src/app/publisher/site-list/site-list-item/site-list-item.component.scss, src/styles.scss, src/styles/_common.scss, src/styles/_keyframes.scss
- increase clickable space for links inside table rows
- add animation for arrow link to indicate when is hovered
- increase clickable space for status select
=> PAN-356: Ux improvements for list of sites and campaign and ads:

src/app/admin/dashboard/dashboard.component.html, src/app/admin/dashboard/dashboard.component.scss, src/app/advertiser/campaign-list/campaign-list-item/campaign-list-item.component.scss, src/app/advertiser/campaign-list/campaign-list.component.scss, src/app/advertiser/dashboard/dashboard.component.html, src/app/common/components/header/header.component.html, src/app/common/components/header/header.component.scss, src/app/common/components/table-navigation/table-navigation.component.html, src/app/common/components/table-navigation/table-navigation.component.scss, src/app/publisher/site-list/site-list-item/site-list-item.component.scss, src/app/settings/billing/billing-history/billing-history-withdrawal/billing-history-withdrawal.component.scss, src/app/settings/billing/billing-history/billing-history.component.html, src/app/settings/billing/billing-history/billing-history.component.scss, src/app/settings/billing/billing.component.scss, src/app/settings/billing/user-wallet/user-wallet.component.html, src/app/settings/billing/user-wallet/user-wallet.component.scss, src/app/settings/settings-navigation/settings-navigation.component.html, src/app/settings/settings-navigation/settings-navigation.component.scss, src/styles/_media-queries.scss, src/styles/_mixins.scss
- fix the size of router outlet for different desktop sizes
- create the most common style mixins
- Bemize navigation settings and user wallet
- user wallet should be adjusted from screens larger than 798px
=> PAN-290: Responsiveness and migration to mixin based approach part1:

src/app/common/components/targeting/targeting.helpers.ts
- add todo containing task id for future improvement
=> PAN-382: Adjust targeting helpers for custom values and corner cases

CHANGELOG.md, src/app/admin/finances/finances-settings.component.html, src/app/admin/finances/finances-settings.component.ts, src/app/advertiser/edit-campaign/edit-campaign-basic-info/edit-campaign-basic-information.component.html, src/app/advertiser/edit-campaign/edit-campaign-basic-info/edit-campaign-basic-information.component.ts, src/app/common/components/chart/chart-settings/chart-settings.helpers.ts, src/app/common/dialog/withdraw-funds-dialog/withdraw-funds-dialog.component.html, src/app/common/dialog/withdraw-funds-dialog/withdraw-funds-dialog.component.ts
Whole app should be based on env currencies
=> All currency codes and symbols should be environment based

src/app/advertiser/campaign-list/campaign-list.component.html, src/app/advertiser/campaign-list/campaign-list.component.scss, src/app/advertiser/dashboard/dashboard.component.html, src/app/advertiser/dashboard/dashboard.component.scss, src/app/common/components/chart-filter-by-type/chart-filter-by-type.component.scss, src/app/publisher/dashboard/dashboard.component.html, src/app/publisher/dashboard/dashboard.component.scss, src/app/publisher/site-list/site-list.component.html, src/app/publisher/site-list/site-list.component.scss, src/styles/_mixins.scss, src/styles/_normalize.scss
site list table and campaign list table should be scrollable under 1100px
- dashboard charts should be visible and readable on smaller screens
- bemize campaign list
=>  PAN-290: Adjust panel for small desktop screens part 3

src/app/advertiser/campaign-details/ad-list/ad-list-item/ad-list-item.component.html, src/app/advertiser/campaign-details/ad-list/ad-list-item/ad-list-item.component.ts, src/app/advertiser/campaign-details/campaign-details.component.html, src/app/advertiser/campaign-details/campaign-details.component.ts, src/app/advertiser/campaign-list/campaign-list-item/campaign-list-item.component.html, src/app/advertiser/campaign-list/campaign-list-item/campaign-list-item.component.ts, src/app/advertiser/campaign-list/campaign-list.component.html, src/app/advertiser/campaign-list/campaign-list.component.ts, src/app/advertiser/edit-campaign/edit-campaign-summary/edit-campaign-summary.component.html, src/app/common/components/chart/chart-settings/chart-settings.helpers.ts, src/app/common/components/header/header.component.html, src/app/common/components/header/header.component.scss, src/app/common/components/header/header.component.ts, src/app/common/dialog/withdraw-funds-dialog/withdraw-funds-dialog.component.html, src/app/common/dialog/withdraw-funds-dialog/withdraw-funds-dialog.component.ts, src/app/common/pipes/adshares-token.pipe.ts, src/app/common/utilities/consts.ts, src/app/publisher/site-details/ad-units/ad-units.component.html, src/app/publisher/site-details/ad-units/ad-units.component.ts, src/app/publisher/site-list/site-list-item/site-list-item.component.html, src/app/publisher/site-list/site-list-item/site-list-item.component.ts, src/app/publisher/site-list/site-list.component.html, src/app/publisher/site-list/site-list.component.ts, src/app/settings/billing/billing-history/billing-history-withdrawal/billing-history-withdrawal.component.html, src/app/settings/billing/billing-history/billing-history-withdrawal/billing-history-withdrawal.component.ts, src/app/settings/billing/user-wallet/user-wallet.component.html, src/app/settings/billing/user-wallet/user-wallet.component.ts, src/app/settings/settings-navigation/settings-navigation.component.html, src/app/settings/settings-navigation/settings-navigation.component.scss, src/app/settings/settings-navigation/settings-navigation.component.ts
- pipe should be suitable for formatting crypto and currency values
- changed name of the pipe to formatMoney
- adjust decimal places for money data
=> PAN-387: Presentation and formatting of money values in the panel

src/app/publisher/site-list/site-list.component.html, src/app/publisher/site-list/site-list.component.scss
- site list table should be scrollable under 1100px
- bemize site list
=> PAN-290: Adjust panel for small desktop screens part 4:

src/app/common/components/targeting/targeting-custom-option-input/targeting-custom-option-input.component.scss, src/app/common/components/targeting/targeting-select/targeting-select.component.html, src/app/common/components/targeting/targeting-select/targeting-select.component.scss, src/app/common/pipes/adshares-token.pipe.ts, src/app/settings/billing/user-wallet/user-wallet.component.html, src/app/settings/billing/user-wallet/user-wallet.component.scss, src/styles/_mixins.scss
…re + minor improvements (#646)
- Bemize and fix styles for targeting select component
- Remove space between currency symbol and value
- When your wallet is equal 0 there should be only 2 decimal values
=> Responsiveness

src/app/admin/admin.module.ts, src/app/admin/admin.service.ts, src/app/admin/dashboard/dashboard.component.ts, src/app/admin/user-list/user-list.component.html, src/app/admin/user-reports/user-reports.component.html, src/app/admin/user-reports/user-reports.component.scss, src/app/admin/user-reports/user-reports.component.ts
Date selecting is working but is not user friendly: selected period (day, week, 30 days) does not updates in UI.
=> PAN-402 Add user events statistics report

src/app/auth.service.ts, src/app/common/request.interceptor.ts, src/app/session.service.ts, src/app/store/advertiser/advertiser.reducers.ts, src/app/store/auth/auth.reducers.ts, src/app/store/publisher/publisher.reducers.ts
Two notable changes:
1. Added to SessionService
```
isActive: boolean;
```
If session is active, it means that user did not log out and popup after HTTP 401 should be shown.
2. Do not restore initial state after succesfull log out. It suceeded with js error and `GET_CURRENT_BALANCE` was executed infinitely. Error was present when user logged out from site details.
=> PAN-398 Fix do not display popup after log out

src/app/admin/admin.service.ts, src/app/admin/dashboard/dashboard.component.ts, src/app/admin/finances/finances-settings.component.html, src/app/admin/finances/finances-settings.component.scss, src/app/admin/finances/finances-settings.component.ts, src/app/models/app-state.model.ts, src/app/models/settings.model.ts, src/app/store/admin/admin.actions.ts, src/app/store/admin/admin.effects.ts, src/app/store/admin/admin.reducers.ts
wip status can be removed after adserver merge (https://github.com/adshares/adserver/pull/861)
=> Add operator wallet status

CHANGELOG.md, src/app/advertiser/edit-campaign/edit-campaign-create-ads/edit-campaign-create-ads.component.html, src/app/advertiser/edit-campaign/edit-campaign-create-ads/edit-campaign-create-ads.component.ts, src/app/common/components/banner-preview/banner-preview.component.html, src/app/common/components/banner-preview/banner-preview.component.ts, src/app/models/classifier.model.ts, src/app/publisher/classifier/classifier-list-item/classifier-list-item.component.html
* Fix banner size in internal classifier (publisher)
* Fix banner size for popup
* Fix banner size for html upload
* update CHANGELOG
=> Fix banner size in internal classifier (publisher) (#722)

CHANGELOG.md, src/app/advertiser/edit-campaign/edit-campaign-conversion/edit-campaign-conversion.component.html, src/app/advertiser/edit-campaign/edit-campaign-conversion/edit-campaign-conversion.component.ts, src/app/models/campaign.model.ts, src/app/models/initial-state/campaign.ts
depends on PR https://github.com/adshares/adserver/pull/931
=> Remove conversion budget

CHANGELOG.md, src/app/publisher/publisher.module.ts, src/app/publisher/site-details/domain-checker/domain-checker.component.html, src/app/publisher/site-details/domain-checker/domain-checker.component.scss, src/app/publisher/site-details/domain-checker/domain-checker.component.ts, src/app/publisher/site-details/site-details.component.html, src/app/publisher/site-details/site-details.component.scss
* Add site domain check
* Styles and messages.
=> Add site domain check component (#729)

CHANGELOG.md, src/app/advertiser/edit-campaign/edit-campaign-conversion/edit-campaign-conversion.component.ts
Requires adserver https://github.com/adshares/adserver/pull/956
=> Add conversion editing

src/app/common/components/table-navigation/table-navigation.component.ts, src/app/models/site.model.ts, src/app/publisher/dialogs/site-code-dialog/site-code-dialog.component.html, src/app/publisher/dialogs/site-code-dialog/site-code-dialog.component.scss, src/app/publisher/dialogs/site-code-dialog/site-code-dialog.component.ts, src/app/publisher/publisher.service.ts, src/app/publisher/site-details/ad-units/ad-units.component.html, src/app/publisher/site-details/ad-units/ad-units.component.ts, src/app/publisher/site-details/site-details.component.html, src/app/publisher/site-details/site-details.component.scss, src/app/publisher/site-details/site-details.component.ts
Options' descriptions must be reviewed - _reviewed_
=> Get code for all zones

.travis.yml, CHANGELOG.md, src/app-settings/app-settings.ts, src/app/auth/auth.component.html, src/app/auth/auth.component.scss, src/app/auth/auth.component.ts, src/app/auth/login/login.component.html, src/app/auth/login/login.component.scss, src/app/auth/register/register.component.html, src/app/auth/register/register.component.scss, src/app/auth/reset-password/reset-password.component.scss, src/environments/environment.ts, src/environments/environment.ts.template, src/styles/_colors.scss, src/styles/_forms.scss, src/styles/_typography.scss
* Login page info
* Benefits info on the login page info
* v1.5.7
* Travis fix
* Travis fix
* Fix CSS
=> Login page info (#758)

CHANGELOG.md, bin/build-index-html.sh, bin/build-index.js, bin/build-preview-html.sh, bin/replace-index-with-preview.sh, deploy/build.sh, deploy/crontablist.sh, deploy/nginx-server.conf, scripts/build.sh, src/app/admin/admin-routing.module.ts, src/app/admin/admin.module.ts, src/app/admin/admin.service.ts, src/app/admin/dashboard/dashboard.component.html, src/app/admin/dashboard/dashboard.component.scss, src/app/admin/dashboard/dashboard.component.ts, src/app/admin/panel-placeholders-settings/panel-placeholders-settings.component.html, src/app/admin/panel-placeholders-settings/panel-placeholders-settings.component.scss, src/app/admin/panel-placeholders-settings/panel-placeholders-settings.component.ts, src/app/admin/privacy-and-terms-settings/privacy-and-terms-settings.component.html, src/app/app-routing.module.ts, src/app/common/components/settings-menu-item/settings-menu-item.component.scss, src/app/models/app-state.model.ts, src/app/models/settings.model.ts, src/app/store/admin/admin.actions.ts, src/app/store/admin/admin.effects.ts, src/app/store/admin/admin.reducers.ts, src/index.html.template
Added: cron
Changed: nginx, build scripts
=> Edit index

CHANGELOG.md, src/app/admin/admin.module.ts, src/app/admin/admin.service.ts, src/app/admin/dashboard/dashboard.component.ts, src/app/admin/general-settings/bid-strategy/bid-strategy.component.html, src/app/admin/general-settings/bid-strategy/bid-strategy.component.scss, src/app/admin/general-settings/bid-strategy/bid-strategy.component.ts, src/app/admin/general-settings/general-settings.component.html, src/app/admin/general-settings/rejected-domains/rejected-domains.component.html, src/app/admin/general-settings/rejected-domains/rejected-domains.component.scss, src/app/admin/general-settings/rejected-domains/rejected-domains.component.ts, src/app/admin/publisher-list/publisher-list.component.html, src/app/admin/user-list/user-list.component.html, src/app/models/app-state.model.ts, src/app/models/campaign.model.ts, src/app/models/settings.model.ts, src/app/publisher/edit-site/edit-site-basic-info/edit-site-basic-information.component.html, src/app/publisher/edit-site/edit-site-basic-info/edit-site-basic-information.component.ts, src/app/publisher/publisher.service.ts, src/app/store/admin/admin.actions.ts, src/app/store/admin/admin.effects.ts, src/app/store/admin/admin.reducers.ts, src/app/store/common/common.effects.ts
Requires updated adserver (bid strategy & domain rejecting endpoints)
=> Add bid strategy and fix user search

CHANGELOG.md, package.json, src/app/api/config.service.ts, src/app/common/dialog/add-funds-dialog/add-funds-dialog.component.html, src/app/common/dialog/add-funds-dialog/add-funds-dialog.component.scss, src/app/common/dialog/add-funds-dialog/add-funds-dialog.component.ts, src/app/models/settings.model.ts, src/app/settings/settings.service.ts, src/styles/_forms.scss, src/styles/_typography.scss
* Invoice form
* Download invoice
* Update changelog
=> Invoices (#818)

CHANGELOG.md, src/app/advertiser/edit-campaign/edit-campaign-create-ads/edit-campaign-create-ads.component.html, src/app/advertiser/edit-campaign/edit-campaign-create-ads/edit-campaign-create-ads.component.ts, src/app/models/enum/link.enum.ts
=> link to wiki how to add an html ad

src/app/auth/auth.component.html, src/app/auth/auth.component.ts, src/app/common/components/header/header.component.html, src/app/common/components/header/header.component.ts, src/app/common/info/info-page/info-page.component.html, src/app/common/info/info-page/info-page.component.ts, src/app/models/info.model.ts
Add landing page link to logo in header
Add landing page link to logo in login page
Add link 'Powered by Adshares'
=> Landing page links

CHANGELOG.md, src/app/common/components/targeting/targeting-select/targeting-select.component.scss, src/app/publisher/classifier/classifier-list-item/classifier-list-item.component.html, src/app/publisher/classifier/classifier-list-item/classifier-list-item.component.scss, src/styles/_material-override.scss
Classifier filtering and Targeting & exclusions text and backgrounds contrasting colors set.
=> Filter color dark mode
